import type { LegalSection } from "@/types/legal";

export const TERMS_LAST_UPDATED = "30th July 2026";

export const TERMS_SECTIONS: LegalSection[] = [
  {
    title: "Introduction",
    paragraphs: [
      "This Site/Application/Service is operated and provided by Playmates (\"Us\", \"Our\", \"We\", or \"Playmates\"), a Nepal-based sports technology company. We organise and facilitate sports and recreational activities, and provide an internet-based booking platform for Our own as well as third-party sports venues, coaching sessions, fitness sessions, tournaments, events, and related activities through Our Site, either directly or through Our affiliates and third-party service providers (\"Primary Services\").",
      "On Our Site We also provide a community feature that allows Customers to find playmates, connect with groups, and join sports games and activities being organised near their locality (\"Secondary Services\"). The Primary Services and Secondary Services, together with the Site, are collectively referred to as the \"Services\". These Terms and Conditions (\"User Terms\") are a legal contract between you and Us.",
      "Subject to these User Terms, you are hereby granted a non-exclusive, limited, non-transferable, non-sublicensable, freely revocable licence to use the Service for your personal, non-commercial use only and as permitted by the features of the Service. Playmates reserves all rights not expressly granted herein.",
      "These User Terms apply to your visit to and use of the Site, whether through a computer, a mobile phone, or any other device, the Service, and all information, recommendations, and/or services provided to you on or through the Site.",
      "This document is an electronic record. It is generated by a computer system and does not require any physical or digital signature.",
      "By successfully registering your account with Us, you consent to be bound by these User Terms. Please read and understand all of these User Terms before you use the Site. If you do not accept any part of these User Terms, please do not use the Site or avail any of the Services. Your agreement to these User Terms is a binding agreement between you and Playmates in respect of your use of the Site and Services.",
      "Your acceptance of these User Terms includes your acceptance of Our Privacy Policy.",
      "By accepting these User Terms, you also allow Playmates to send you promotional emails and SMS alerts from time to time. You may opt out of promotional communications at any time.",
    ],
  },
  {
    title: "Definitions",
    paragraphs: [
      "All defined and capitalised terms in these User Terms have the meaning assigned to them below:",
    ],
    definitions: [
      { term: "Account", def: "the account created by or for the Customer on the Site for availing the Services." },
      { term: "Additional Fee", def: "any duty, tax, or third-party/government charge not included in the Order Value but payable to avail Services under Applicable Law." },
      { term: "Applicable Law(s)", def: "all applicable statutes, acts, laws, ordinances, rules, regulations, notifications, guidelines, policies, directions, and orders of any governmental authority, tribunal, or court of Nepal." },
      { term: "Application", def: "the mobile application Playmates, owned and updated by Playmates from time to time." },
      { term: "Convenience Fee", def: "the fee payable by the Customer to Playmates for the technology services offered by Playmates, chargeable on every Order made through the Site, exclusive of applicable taxes." },
      { term: "Cancellation Fee", def: "the fee payable towards cancellation of an Order by a Customer, exclusive of applicable taxes." },
      { term: "Customer / you", def: "a person who has an Account on the Site." },
      { term: "E-Wallet", def: "a pre-paid instrument that can be used to make payments on the Site." },
      { term: "Force Majeure Event", def: "any event arising due to a cause beyond the reasonable control of Playmates." },
      { term: "Membership Plan / Session Pass", def: "a pass, reservation, or membership plan purchased through the Site that allows the holder, subject to its terms, to access, attend, or participate in a venue, sport, fitness session, or activity identified in such plan." },
      { term: "Order", def: "an order placed by a Customer to avail Services through the Site." },
      { term: "Order Value", def: "the amount in Nepalese Rupees reflected on the Site as payable for a specific Order, exclusive of applicable taxes." },
      { term: "Registration Data", def: "the present, valid, true, and accurate name, email ID, phone number, and other information required by Playmates from the Customer for registration on the Application." },
      { term: "Services", def: "a joint reference to the Primary Services and the Secondary Services." },
      { term: "Site", def: "the Application, the website owned and operated by Playmates, and any other platform owned and developed by Us that enables use of the Services." },
      { term: "Total Fee", def: "the sum of the Order Value, Convenience Fee, Cancellation Fee, Additional Fee, and applicable taxes." },
    ],
  },
  {
    title: "Eligibility",
    paragraphs: [
      "You are eligible to use the Services only if you are competent to enter into a binding contract under Applicable Laws.",
      "If you reside in a jurisdiction that restricts use of the Service or the ability to enter into this User Terms due to age, your use of the Services shall bind your legal guardian to these User Terms.",
    ],
  },
  {
    title: "Registration and Account",
    paragraphs: [
      "To access password-restricted areas of the Site and certain Services, you are required to successfully register an Account with Us by providing your Registration Data.",
      "You shall ensure that the Registration Data you provide is accurate, complete, current, valid, and true, and is kept updated. We bear no liability for false, incomplete, outdated, or incorrect Registration Data provided by you.",
      "You are solely responsible for maintaining the confidentiality of your Account credentials and will be liable for all activities and transactions carried out through your Account, whether initiated by you or a third party. Your Account cannot be transferred, assigned, or sold. We are not liable for any loss you may incur as a result of unauthorised use of your Account, with or without your knowledge.",
      "We reserve the right to suspend or terminate your Account with immediate effect, for an indefinite period, if We have reason to believe your Registration Data is incorrect or false, that the security of your Account has been compromised, or for any other reason We find just or equitable.",
    ],
  },
  {
    title: "Booking, Orders and Payments",
    paragraphs: [
      "Customers may place Orders through the Site to book sports venues, coaching or fitness sessions, tournaments, marathons, events, and Membership Plans offered by Us or by third-party venue and vendor partners.",
      "The Order Value, Convenience Fee, and any Additional Fee will be displayed at the time of booking. Payment may be made through the payment methods enabled on the Site, including cards, digital wallets, bank transfer, or E-Wallet balance.",
      "An Order is confirmed only upon successful payment and receipt of a confirmation from Us. We are not responsible for delays or failures caused by payment gateways, banks, or third-party payment processors.",
    ],
  },
  {
    title: "Cancellation, Rescheduling and Refunds",
    paragraphs: [
      "Cancellation and rescheduling of an Order are subject to the specific cancellation policy displayed for that venue, session, or event at the time of booking, and may attract a Cancellation Fee.",
      "Refunds, where applicable, will be processed to the original payment method or E-Wallet within a reasonable time after approval of the cancellation request.",
      "We reserve the right to cancel an Order due to unavailability of the venue, Force Majeure Event, or any reason beyond Our reasonable control, in which case a full refund of the Order Value will be issued unless otherwise stated.",
    ],
  },
  {
    title: "Code of Conduct",
    paragraphs: [
      "When using the Services, you agree not to: provide false or misleading information; misuse, damage, or disrupt any venue, facility, or equipment booked through the Site; harass, threaten, or behave abusively towards other Customers, coaches, venue staff, or partners; use the Site for any unlawful, fraudulent, or unauthorised purpose; or attempt to interfere with the security or proper functioning of the Site.",
      "We reserve the right to suspend or terminate the Account of any Customer found in breach of this Code of Conduct, without liability to Us.",
    ],
  },
  {
    title: "Third-Party Venues, Coaches and Content",
    paragraphs: [
      "Many venues, coaches, academies, gyms, and events listed on the Site are owned, operated, or organised by independent third parties (\"Partners\"). Playmates acts as a technology platform facilitating discovery and booking of such Partners' offerings and is not itself the provider of the underlying venue, coaching, fitness, or event service.",
      "We make reasonable efforts to verify listings but do not guarantee the accuracy, quality, safety, or legality of any Partner's venue, facility, or service. Your interactions and any disputes with a Partner are strictly between you and that Partner, and Playmates shall not be a party to such disputes.",
      "Sports and fitness activities carry an inherent risk of injury. You participate in any venue, session, event, or activity booked through the Site at your own risk and are responsible for assessing your own fitness and the suitability of the activity for yourself.",
    ],
  },
  {
    title: "Intellectual Property",
    paragraphs: [
      "The Site, the Application, and all content, trademarks, logos, and material made available thereon (including the \"Playmates\" name and logo) are the exclusive property of Playmates or Our licensors, and are protected under Applicable Law. Nothing in these User Terms grants you any right to use Our trademarks, logos, or brand features without Our prior written consent.",
    ],
  },
  {
    title: "Disclaimer of Warranties and Limitation of Liability",
    paragraphs: [
      "The Site and Services are provided on an \"as is\" and \"as available\" basis, without warranties of any kind, whether express or implied, to the fullest extent permitted by Applicable Law.",
      "To the maximum extent permitted by Applicable Law, Playmates shall not be liable for any indirect, incidental, special, or consequential damages, or any loss of profits, data, or goodwill, arising out of or in connection with your use of the Site or Services, including any act or omission of a Partner.",
    ],
  },
  {
    title: "Indemnification",
    paragraphs: [
      "You agree to indemnify and hold harmless Playmates, Our officers, employees, and affiliates from any claim, loss, liability, or expense (including reasonable legal fees) arising out of your breach of these User Terms, your misuse of the Services, or your violation of any Applicable Law or third-party right.",
    ],
  },
  {
    title: "Term, Suspension and Termination",
    paragraphs: [
      "These User Terms remain in effect for as long as you use the Site or hold an Account. We may suspend or terminate your access to the Site or Services at any time, with or without notice, for conduct that We believe violates these User Terms or is otherwise harmful to other users, Partners, or Us.",
      "You may stop using the Services and request deletion of your Account at any time by contacting Us.",
    ],
  },
  {
    title: "Force Majeure",
    paragraphs: [
      "Playmates shall not be liable for any failure or delay in performance of its obligations under these User Terms resulting from a Force Majeure Event, including natural disasters, government action, strikes, internet or telecommunication failures, or other causes beyond Our reasonable control.",
    ],
  },
  {
    title: "Privacy",
    paragraphs: [
      "Your use of the Site and Services is also governed by Our Privacy Policy, which describes how We collect, use, and protect your personal information. By using the Site, you consent to the collection and use of your information as described therein.",
    ],
  },
  {
    title: "Governing Law and Dispute Resolution",
    paragraphs: [
      "These User Terms are governed by and construed in accordance with the laws of Nepal, including the Electronic Transactions Act, 2063 (2008). Subject to Applicable Law, the courts at Birgunj, Nepal shall have exclusive jurisdiction over any dispute arising out of or in connection with these User Terms.",
    ],
  },
  {
    title: "Amendments to These Terms",
    paragraphs: [
      "We may update or modify these User Terms from time to time. The updated version will be posted on the Site with a revised \"Last Updated\" date. Your continued use of the Site or Services after any such update constitutes your acceptance of the revised User Terms.",
    ],
  },
  {
    title: "Contact Us",
    paragraphs: [
      "If you have any questions about these User Terms, please contact Us at:",
      "Playmates\nBypass road, opposite Himal Hotel, Ward no. 8, Birgunj, Nepal\nEmail: admin@askplaymates.com\nPhone: 9855074067, 9855035067",
    ],
  },
];
